use serde::{Deserialize, Serialize};
use serde_json::Result;

const AVAILABLE_ELEMENTS: [&str; 119] = [
    "hydrogen", "helium", "lithium", "beryllium", "boron", "carbon", "nitrogen", "oxygen",
    "fluorine", "neon", "sodium", "magnesium", "aluminium", "silicon", "phosphorus", "sulfur",
    "chlorine", "argon", "potassium", "calcium", "scandium", "titanium", "vanadium", "chromium",
    "manganese", "iron", "cobalt", "nickel", "copper", "zinc", "gallium", "germanium", "arsenic",
    "selenium", "bromine", "krypton", "rubidium", "strontium", "yttrium", "zirconium", "niobium",
    "molybdenum", "technetium", "ruthenium", "rhodium", "palladium", "silver", "cadmium", "indium",
    "tin", "antimony", "tellurium", "iodine", "xenon", "cesium", "barium", "lanthanum", "cerium",
    "praseodymium", "neodymium", "promethium", "samarium", "europium", "gadolinium", "terbium",
    "dysprosium", "holmium", "erbium", "thulium", "ytterbium", "lutetium", "hafnium", "tantalum",
    "tungsten", "rhenium", "osmium", "iridium", "platinum", "gold", "mercury", "thallium", "lead",
    "bismuth", "polonium", "astatine", "radon", "francium", "radium", "actinium", "thorium",
    "protactinium", "uranium", "neptunium", "plutonium", "americium", "curium", "berkelium",
    "californium", "einsteinium", "fermium", "mendelevium", "nobelium", "lawrencium",
    "rutherfordium", "dubnium", "seaborgium", "bohrium", "hassium", "meitnerium", "darmstadtium",
    "roentgenium", "copernicium", "nihonium", "flerovium", "moscovium", "livermorium", "tennessine",
    "oganesson", "ununennium"
];

#[derive(Serialize, Deserialize)]
struct Element {
    name: String,
    root: String,
    symbol: String,
    appearance: String,
    atomic_mass: f64,
    boil: f64,
    category: String,
    density: f64,
    discovered_by: String,
    melt: f64,
    molar_heat: f64,
    named_by: String,
    number: i64,
    period: i64,
    group: i64,
    phase: String,
    summary: String,
    xpos: i64,
    ypos: i64,
    wxpos: i64,
    wypos: i64,
    shells: Vec<i64>,
    electron_configuration: String,
    electron_configuration_semantic: String,
    electron_affinity: f64,
    electronegativity_pauling: f64,
    ionization_energies: Vec<f64>,
    oxidation_states: Vec<i64>,
    cpk_hex_color: String,
    block: String,
}
